name: task_manager
version: 1.0.0+1
description: Task manager app with camera, sensors, and GPS
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  sensors_plus: ^4.0.2
  vibration: ^3.1.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.7
  image: ^4.1.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
